######################################################################
# Automatically generated by qmake (3.0) ?? 1? 20 21:41:28 2017
######################################################################

TEMPLATE = app
TARGET = graphc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
